Algoritmo "Exercicio3"

// Autor(a): Erik Miqueias Pereira Costa
// Data: 03/08/2026

Var
// Seção de Declarações das variáveis
numero1, numero2: real

Inicio
// Seção de Comandos
	escreval("Digite o primeiro número: ");
  leia(numero1)
  escreval("Digite o segundo número: ");
  leia(numero2);
  
  escreva("A média aritmética do número ", numero1, " e o número ", numero2, " é: ", (numero1 + numero2) / 2) // exibe a média entre a variavel numero1 e numero2


fimalgoritmo