Algoritmo "Exercicio1"

// Autor(a): Erik Miqueias Pereira Costa
// Data: 03/08/2026

Var
// Seção de Declarações das variáveis
numero: inteiro

Inicio
// Seção de Comandos
	escreval("Digite um número: ");
  leia(numero);
  
  escreval("O dobro do número ", numero, " é: ", numero * 2); // exibe o dobro do número do usuário
  escreval("O triplo do número ", numero, " é: ", numero * 3); // exibe o triplo do número do usuário


fimalgoritmo