Algoritmo "Exercicio7"

// Autor(a): Erik Miqueias Pereira Costa
// Data: 03/08/2026

Var
// Seção de Declarações das variáveis
peso, altura: real

Inicio
// Seção de Comandos
	escreval("Digite seu peso: KG");
  leia(peso);
  escreval("Digite sua altura: M");
  leia(altura);
  
  escreva("Seu IMC é: ", peso / (altura * altura):4:2); // calcula o IMC e formata para duas casas decimais


fimalgoritmo