Algoritmo "Exercicio8"

// Autor(a): Erik Miqueias Pereira Costa
// Data: 03/08/2026

Var
// Seção de Declarações das variáveis
temperaturaEmCelsius, conversaoEmFarenheit: real

Inicio
// Seção de Comandos
	escreval("Digite a temperatura em Celsius C°: ");
  leia(temperaturaEmCelsius);
  
  escreval("Conversão em Farenheit F°: ", (temperaturaEmCelsius * 9 / 5) + 32); // exibe a temperatura convertida em F°



fimalgoritmo