Algoritmo "Exercicio2"

// Autor(a): Erik Miqueias Pereira Costa
// Data: 03/08/2026

Var
// Seção de Declarações das variáveis
numero: inteiro

Inicio
// Seção de Comandos
	escreval("Digite um número para verificar seu SUCESSOR e ANTECESSOR: ");
	leia(numero)
  
  escreval("O SUCESSOR do número ", numero, " é: ", numero + 1); // exibe o numero + 1 sendo seu sucessor
  escreva("O ANTECESSOR do número ", numero, " é: ", numero - 1); // exibe o numero - 1 sendo seu antecessor

fimalgoritmo