Algoritmo "Exercicio5"

// Autor(a): Erik Miqueias Pereira Costa
// Data: 03/08/2026

Var
// Seção de Declarações das variáveis
salarioHora: real
horasTrabalhadas: inteiro

Inicio
// Seção de Comandos
	salarioHora <- 7.37
	escreval("Digite suas horas trabalhadas para o cálculo de salário final com base no salário mínimo brasileiro: ");
  leia(horasTrabalhadas);
  escreva("Seu salário por horas trabalhadas é: R$", salarioHora * horasTrabalhadas); // multiplica o salario por hora baseado no salário mínimo pela quantidade de horas trabalhadas



fimalgoritmo