Algoritmo "Exercicio10"

// Autor(a): Erik Miqueias Pereira Costa
// Data: 03/08/2026

Var
// Seção de Declarações das variáveis
numero1, numero2: inteiro

Inicio
// Seção de Comandos
	escreval("Digite o primeiro número: ");
  leia(numero1);
  escreval("Digite o segundo número: ");
  leia(numero2);
  
  // Exibe cada operação com os dois números
  
  escreval("Adição: ", numero1 + numero2);
  escreval("Subtração: ", numero1 - numero2);
  escreval("Multiplicação: ", numero1 * numero2);
	escreval("Divisão: ", numero1 / numero2);

fimalgoritmo