Algoritmo "Exercicio4"

// Autor(a): Erik Miqueias Pereira Costa
// Data: 03/08/2026

Var
// Seção de Declarações das variáveis
base: inteiro
altura: inteiro
area: real

Inicio
// Seção de Comandos
	escreval("Digite a base do triângulo: ");
  leia(base)
  escreval("Digite a altura do triângulo: ");
  leia(altura)
  
  area <- (base * altura) / 2 // armazena o calculo da área do triângulo
  escreva("A área do triângulo é: ", area)

fimalgoritmo