Algoritmo "Exercicio11"

// Autor(a): Erik Miqueias Pereira Costa
// Data: 03/08/2026

Var
// Seção de Declarações das variáveis
numero, i: inteiro

Inicio
// Seção de Comandos
	escreval("Digite um número: ");
  leia(numero);
  
 	para i de 1 ate numero faca
  	se i % 5 = 0 entao // verifica se o i é divisivel por 5 com resto 0, se for é multiplo de 5 e exibe
    	escreva(i, " ")
   	fimse
 fimpara



fimalgoritmo